services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: java
      POSTGRES_PASSWORD: java
      POSTGRES_DB: java
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: